In [3]:
import numpy as np
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.arange(1,11,2.1, dtype=float)

array([1. , 3.1, 5.2, 7.3, 9.4])

In [12]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.random.rand(3)

array([0.30600182, 0.12620658, 0.50812751])

In [19]:
np.random.rand(3,2)

array([[0.96530147, 0.11100467],
       [0.36877087, 0.55949259],
       [0.40588671, 0.37070723]])

In [20]:
np.random.randn(4,4)

array([[-0.63030737, -0.90259536, -0.39525796,  0.3495768 ],
       [ 1.19943701,  0.27462688,  0.80573635, -0.2779183 ],
       [ 0.83561768, -0.31907095,  0.74603813,  0.55622178],
       [-1.88897634, -1.10437756,  1.07485227, -1.76132541]])

In [23]:
np.random.randint (1,100)

52

In [24]:
np.random.randint (1,100,10)

array([ 8, 78, 18, 58, 93, 26,  1, 56, 48, 85])

In [25]:
np.random.randint (1,100,(2,3))


array([[87, 99, 94],
       [31, 73, 73]])

In [28]:
array_arange = np.arange(16)

In [31]:
array_randint = np.random.randint(0,100,10)

In [30]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
array_randint

array([48, 62, 31, 93, 68, 25, 55, 25, 40, 15])

In [33]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
array_randint.max()

93

In [36]:
array_randint.min()

15

In [37]:
array_randint.argmax()

3

In [38]:
array_randint.argmin()

9

In [40]:
array_arange.shape

(16,)

In [41]:
array_arange.size

16

In [42]:
array_arange.dtype

dtype('int32')

In [43]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
array_arange.reshape(4,4).shape

(4, 4)